
const booksData = [
  { 
    id:"whispers", 
    title: "Whispers of the Stars", 
    author: "Amelia Frost", 
    category: "fiction", 
    language: "english", 
    image: "https://i.postimg.cc/t4NC5260/wishpers.jpg", 
    description: "A mesmerizing tale of cosmic secrets and destiny. Follow Elara as she discovers she can communicate with celestial bodies and uncovers a prophecy that could save or destroy the universe.",
    rating: 4.7,
    authorImage: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200&h=200&fit=crop&crop=face",
    authorBio: "Amelia Frost is an award-winning author known for her captivating stories that blend science fiction with magical realism. With over 10 published novels, she has won the Nebula Award twice and continues to inspire readers worldwide."
  },
  { 
    id:"hiddenforces", 
    title: "The Hidden Forces", 
    author: "Michael Reed", 
    category: "science", 
    language: "english", 
    image: "https://i.postimg.cc/kgsq8DrR/hiddenforces.jpg", 
    description: "Explore the unseen energies that shape our universe. This groundbreaking book reveals how quantum physics and consciousness are interconnected in ways we're only beginning to understand.",
    rating: 4.3,
    authorImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    authorBio: "Dr. Michael Reed is a theoretical physicist and bestselling author. His work bridges the gap between complex scientific concepts and everyday understanding, making advanced physics accessible to all."
  },
  { 
    id:"the_art_of_stillness", 
    title: "The Art of Stillness", 
    author: "John Parker", 
    category: "non-fiction", 
    language: "english", 
    image: "https://i.postimg.cc/85r2yzYX/theart.jpg", 
    description: "Adventures in going nowhere — reflections on calm and presence. In a world of constant movement, discover the power of staying still and finding peace within.",
    rating: 4.5,
    authorImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    authorBio: "John Parker is a mindfulness teacher and meditation guide with over 20 years of experience. His writings have helped thousands find inner peace in their busy lives."
  },
  { 
    id:"her_legacy", 
    title: "Her Legacy", 
    author: "Guin Archer", 
    category: "fiction", 
    language: "english", 
    image: "https://i.postimg.cc/3RpqXby1/legacy.jpg", 
    description: "A supernatural tale of wolves, destiny, and courage. When a young woman discovers her ancestral powers, she must embrace her legacy to protect her family and the magical world she never knew existed.",
    rating: 4.2,
    authorImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
    authorBio: "Guin Archer is known for her supernatural fiction that explores themes of destiny, family legacy, and the connection between humans and nature. Her novels have been praised for their rich world-building."
  },
  { 
    id:"echoes_of_the_past", 
    title: "Echoes of the Past", 
    author: "Sarah Morgan", 
    category: "biography", 
    language: "english", 
    image: "https://i.postimg.cc/bNLB9nJj/enchoes.jpg", 
    description: "A family saga of memory and reconciliation. This powerful memoir traces three generations of women and the secrets that both divided and united them across decades.",
    rating: 4.6,
    authorImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
    authorBio: "Sarah Morgan writes compelling family sagas and memoirs that explore the complexities of memory, relationships, and reconciliation across generations."
  },
  { 
    id:"journey_within", 
    title: "A Journey Within", 
    author: "Sophia Adams", 
    category: "non-fiction", 
    language: "english", 
    image: "https://i.postimg.cc/cHQDggj9/journey.jpg", 
    description: "A guide to inner exploration and self-discovery. This transformative book offers practical exercises and profound insights for anyone seeking deeper meaning and purpose in life.",
    rating: 4.4,
    authorImage: "https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=200&h=200&fit=crop&crop=face",
    authorBio: "Sophia Adams is a spiritual teacher and life coach who has guided thousands through their personal transformation journeys. Her work combines Eastern wisdom with Western practicality."
  },
  { 
    id:"wonders_universe", 
    title: "Wonders of the Universe", 
    author: "Dr. Neil Harper", 
    category: "science", 
    language: "english", 
    image: "https://i.postimg.cc/MZ5DCS8m/wonder.jpg", 
    description: "A stunning tour of cosmic wonders. From the birth of stars to the mysteries of black holes, this book makes the vastness of space accessible and awe-inspiring.",
    rating: 4.8,
    authorImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    authorBio: "Dr. Neil Harper is an astrophysicist and science communicator who has dedicated his career to making complex astronomical concepts understandable and exciting for the general public."
  },
  { 
    id:"chronos_rift", 
    title: "Chronos Rift", 
    author: "Alan Steele", 
    category: "science", 
    language: "english", 
    image: "https://i.postimg.cc/d1qC6hDc/chron.jpg", 
    description: "A thrilling journey through time and space. When a physics experiment goes wrong, a team of scientists finds themselves trapped in different timelines, racing against time to repair the fabric of reality.",
    rating: 4.1,
    authorImage: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=200&h=200&fit=crop&crop=face",
    authorBio: "Alan Steele is a science fiction author known for his hard sci-fi approach and attention to scientific accuracy while maintaining compelling storytelling."
  },
  { 
    id:"big_little_lies", 
    title: "Big Little Lies", 
    author: "Liane Moriarty", 
    category: "mystery", 
    language: "english", 
    image: "https://i.postimg.cc/FRRR1375/big.jpg", 
    description: "A clever, darkly comic novel about families and secrets. Three women, each at a crossroads, find their lives intertwined in ways they never expected in this suspenseful tale.",
    rating: 4.5,
    authorImage: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face",
    authorBio: "Liane Moriarty is the Australian author of seven internationally best-selling novels, including Big Little Lies and The Husband's Secret, which have been adapted into major television series."
  },
  { 
    id:"dune", 
    title: "Dune", 
    author: "Frank Herbert", 
    category: "science", 
    language: "english", 
    image: "https://i.postimg.cc/Y0FmqYsf/dune.jpg", 
    description: "An epic saga of power, survival, and destiny. Set in the distant future amidst a sprawling feudal interstellar empire, Dune tells the story of young Paul Atreides as he navigates political intrigue and ecological challenges on the desert planet Arrakis.",
    rating: 4.7,
    authorImage: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&crop=face",
    authorBio: "Frank Herbert was an American science fiction author best known for the novel Dune and its five sequels. The Dune saga is widely considered one of the greatest science fiction works of all time."
  },
  { 
    id:"educated", 
    title: "Educated", 
    author: "Tara Westover", 
    category: "non-fiction", 
    language: "english", 
    image: "https://i.postimg.cc/JhdyNpws/edu.jpg", 
    description: "A memoir about family, education, and transformation. Tara Westover was seventeen the first time she set foot in a classroom, born to survivalists in the mountains of Idaho. This is her story of pursuing knowledge against all odds.",
    rating: 4.6,
    authorImage: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=200&h=200&fit=crop&crop=face",
    authorBio: "Tara Westover is an American historian and memoirist. Educated is her first book, which became an instant New York Times bestseller and won several awards including the National Book Critics Circle Award."
  },
  { 
    id:"the_martian", 
    title: "The Martian", 
    author: "Andy Weir", 
    category: "science", 
    language: "english", 
    image: "https://i.postimg.cc/tJG4kfBH/martin.jpg", 
    description: "Survival story on Mars. After a dust storm forces his crew to evacuate while thinking him dead, astronaut Mark Watney finds himself stranded on Mars with limited supplies and must use his ingenuity to survive.",
    rating: 4.4,
    authorImage: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face",
    authorBio: "Andy Weir is an American novelist whose debut novel The Martian was adapted into a successful film. He is known for his attention to scientific accuracy in his storytelling."
  },
  { 
    id:"quantum_paradox", 
    title: "The Quantum Paradox", 
    author: "Oliver Grey", 
    category: "science", 
    language: "english", 
    image: "https://i.postimg.cc/SKXQhq58/quantum.jpg", 
    description: "A mind-bending science adventure. When a quantum physicist discovers how to manipulate reality at the subatomic level, she must prevent her technology from falling into the wrong hands while grappling with the ethical implications of her creation.",
    rating: 4.2,
    authorImage: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=200&h=200&fit=crop&crop=face",
    authorBio: "Oliver Grey is a physicist-turned-author who writes scientifically accurate thrillers that explore the ethical implications of emerging technologies."
  },
  { 
    id:"silent_witness", 
    title: "The Silent Witness", 
    author: "Carolyn Arnold", 
    category: "mystery", 
    language: "french", 
    image: "https://i.postimg.cc/2SyrQrzp/silent.jpg", 
    description: "Detective Amanda Steele mystery. When a key witness in a high-profile case turns up dead, Detective Amanda Steele must unravel a complex web of deception before the killer strikes again.",
    rating: 4.0,
    authorImage: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop&crop=face",
    authorBio: "Carolyn Arnold is a bestselling author of police procedurals and cozy mysteries. Her Detective Amanda Steele series has garnered critical acclaim for its authentic portrayal of police work."
  },
  { 
    id:"man_changed_everything", 
    title: "The Man Who Changed Everything", 
    author: "Basil Mahon", 
    category: "biography", 
    language: "english", 
    image: "https://i.postimg.cc/Qx4rxwcg/man.jpg", 
    description: "The life of James Clerk Maxwell. This biography explores the life and work of the brilliant physicist whose equations unified electricity, magnetism, and light, laying the foundation for modern physics.",
    rating: 4.3,
    authorImage: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200&h=200&fit=crop&crop=face",
    authorBio: "Basil Mahon is a science writer and biographer known for making complex scientific concepts and the lives of scientists accessible to general readers."
  },
  { 
    id:"dust_to_destiny", 
    title: "From Dust to Destiny", 
    author: "Steve Colins", 
    category: "fiction", 
    language: "english", 
    image: "https://i.postimg.cc/Rhg2hJJS/dust.jpg", 
    description: "A story about finding purpose in chaos. After losing everything in a natural disaster, a man embarks on a cross-country journey that transforms his understanding of loss, resilience, and what truly matters.",
    rating: 4.1,
    authorImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
    authorBio: "Steve Colins writes character-driven fiction that explores themes of redemption, personal growth, and the human capacity for resilience in the face of adversity."
  },
  { 
    id:"selfish_gene", 
    title: "The Selfish Gene", 
    author: "Richard Dawkins", 
    category: "science", 
    language: "english", 
    image: "https://i.postimg.cc/7YQpy7yQ/selfish.jpg", 
    description: "Classic introduction to evolutionary biology. This groundbreaking work popularized the gene-centered view of evolution and introduced the concept of memes, forever changing how we understand natural selection.",
    rating: 4.5,
    authorImage: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=200&h=200&fit=crop&crop=face",
    authorBio: "Richard Dawkins is an evolutionary biologist, author, and public intellectual. He is an emeritus fellow of New College, Oxford, and was the University of Oxford's Professor for Public Understanding of Science from 1995 to 2008."
  },
  { 
    id:"1984", 
    title: "1984", 
    author: "George Orwell", 
    category: "fiction", 
    language: "english", 
    image: "https://i.postimg.cc/xdL7H4NF/george.jpg", 
    description: "Dystopian classic about surveillance and power. In a totalitarian future where independent thought is persecuted, Winston Smith dares to question the Party and its mysterious leader, Big Brother.",
    rating: 4.7,
    authorImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    authorBio: "George Orwell was an English novelist, essayist, journalist, and critic. His work is characterized by lucid prose, social criticism, opposition to totalitarianism, and support of democratic socialism."
  },
  { 
    id:"gone_girl", 
    title: "Gone Girl", 
    author: "Gillian Flynn", 
    category: "mystery", 
    language: "english", 
    image: "https://i.postimg.cc/j5XF3nXJ/gone.jpg", 
    description: "A twisted thriller about marriage and media. On their fifth wedding anniversary, Nick's wife Amy disappears. Under pressure from the police and a growing media frenzy, Nick's portrait of a blissful union begins to crumble.",
    rating: 4.2,
    authorImage: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200&h=200&fit=crop&crop=face",
    authorBio: "Gillian Flynn is an American author, screenwriter, and former television critic for Entertainment Weekly. Her published works include the bestselling novels Sharp Objects, Dark Places, and Gone Girl."
  },
  { 
    id:"thinking_fast_slow", 
    title: "Thinking, Fast and Slow", 
    author: "Daniel Kahneman", 
    category: "non-fiction", 
    language: "english", 
    image: "https://i.postimg.cc/7YbWX6TP/think.jpg", 
    description: "On human decision-making and bias. Nobel laureate Daniel Kahneman explores the two systems that drive the way we think—System 1, which is fast and intuitive, and System 2, which is slow and deliberate.",
    rating: 4.6,
    authorImage: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200&h=200&fit=crop&crop=face",
    authorBio: "Daniel Kahneman is an Israeli psychologist and economist notable for his work on the psychology of judgment and decision-making, for which he was awarded the 2002 Nobel Memorial Prize in Economic Sciences."
  },
    {
    id: "book1",
    title: "The Power of Subcoision",
    author: "Amelia Frost",
    category: "Popular Books",
    rating: 4.7,
    image: "https://m.media-amazon.com/images/I/81gTwYAhU7L.jpg",
    description: "A poetic and enchanting tale about love, destiny, and the universe beyond the stars.",
    authorImage: "https://i.pravatar.cc/150?img=11",
    authorBio: "Amelia Frost is a fantasy writer known for her lyrical storytelling and cosmic imagination."
  },
  {
    id: "book2",
    title: "Little Monsters",
    author: "James Clear",
    category: "Popular Books",
    rating: 4.5,
    image: "https://i.postimg.cc/Rh64j1nN/9781982198114-p0-v4-s600x595.jpg",
    description: "A suspenseful story about friendship, fear, and the monsters within us all.",
    authorImage: "https://i.pravatar.cc/150?img=12",
    authorBio: "James Clear writes psychological thrillers exploring human behavior and hidden emotions."
  },
  {
    id: "book3",
    title: "Alchemist",
    author: "John Parker",
    category: "Popular Books",
    rating: 4.3,
    image: "https://m.media-amazon.com/images/I/71aFt4+OTOL.jpg",
    description: "A mindful guide to finding peace and clarity in a chaotic world.",
    authorImage: "https://i.pravatar.cc/150?img=13",
    authorBio: "John Parker is a meditation expert who blends philosophy and science in his writing."
  },
  {
    id: "book4",
    title: "Statcy Abrams",
    author: "Grace Collins",
    category: "Popular Books",
    rating: 4.6,
    image: "https://i.postimg.cc/Yqf8gv94/lf-1.webp",
    description: "A moving novel about family, courage, and the power of storytelling.",
    authorImage: "https://i.pravatar.cc/150?img=14",
    authorBio: "Grace Collins writes heartfelt dramas about love, loss, and self-discovery."
  },
  {
    id: "book5",
    title: "Harry Potter",
    author: "J.K Rowling",
    category: "Popular Books",
    rating: 5.0,
    image: "https://i.postimg.cc/gJD1Ngcr/deathly-hallows-us-childrens-edition.jpg",
    description: "A legendary fantasy saga about friendship, magic, and bravery at Hogwarts.",
    authorImage: "https://i.pravatar.cc/150?img=15",
    authorBio: "J.K. Rowling is a British author best known for creating the magical world of Harry Potter."
  },
  {
    id: "book6",
    title: "The Crime and Punishment",
    author: "Fyodor Dostoyevsky",
    category: "Popular Books",
    rating: 4.9,
    image: "https://i.postimg.cc/ryhwpJGs/63897843.jpg",
    description: "A classic psychological novel about guilt, morality, and redemption.",
    authorImage: "https://i.pravatar.cc/150?img=16",
    authorBio: "Fyodor Dostoyevsky is one of the greatest Russian novelists, known for his deep exploration of the human soul."
  },
  {
    id: "book7",
    title: "Famous Last Words",
    author: "Tahereh Mafi",
    category: "Novels",
    rating: 4.2,
    image: "https://i.postimg.cc/YCvG7PJr/famous-last-words.jpg",
    description: "A haunting novel that blends mystery and romance with supernatural elements.",
    authorImage: "https://i.pravatar.cc/150?img=17",
    authorBio: "Tahereh Mafi is a New York Times bestselling author of the 'Shatter Me' series."
  },
  {
    id: "book8",
    title: "Shatter Me",
    author: "Tahereh Mafi",
    category: "Novels",
    rating: 4.8,
    image: "https://i.postimg.cc/0y76rS2W/f7330eaebb0c20f3dced3ea584bf6dbd.jpg",
    description: "A dystopian story about power, love, and survival — where words can be deadly.",
    authorImage: "https://i.pravatar.cc/150?img=18",
    authorBio: "Tahereh Mafi is celebrated for her poetic prose and emotional storytelling."
  },
  {
    id: "book9",
    title: "Caraval",
    author: "Stephanie Garber",
    category: "Novels",
    rating: 4.4,
    image: "https://i.postimg.cc/T1mym5JJ/e8812908937c4d740d60a62494bcb332.jpg",
    description: "A magical journey where nothing is as it seems and every choice has a price.",
    authorImage: "https://i.pravatar.cc/150?img=19",
    authorBio: "Stephanie Garber is known for her imaginative worlds and captivating plots."
  },
  {
    id: "book10",
    title: "Kingdom",
    author: "Tara Quinn",
    category: "Novels",
    rating: 4.1,
    image: "https://i.postimg.cc/qBh0wTV5/3d679f36d39929f49e1a041efc0778e9.jpg",
    description: "An epic tale of betrayal, power, and the fight for a forgotten throne.",
    authorImage: "https://i.pravatar.cc/150?img=20",
    authorBio: "Tara Quinn writes epic fantasies with complex characters and deep moral questions."
  },
  {
    id: "book11",
    title: "The Wicked King",
    author: "Grace Collins",
    category: "Novels",
    rating: 4.5,
    image: "https://i.postimg.cc/v89kDHwX/89d95bc20332b42daa3c1f74a93d5fc5.jpg",
    description: "A thrilling fantasy about deception, love, and the struggle for power.",
    authorImage: "https://i.pravatar.cc/150?img=21",
    authorBio: "Grace Collins is a bestselling fantasy author with a flair for strong female leads."
  },
  {
    id: "book12",
    title: "The Fault",
    author: "Michael Reed",
    category: "Self Improvement",
    rating: 4.4,
    image: "https://m.media-amazon.com/images/I/81a4kCNuH+L.jpg",
    description: "Discover the unseen principles that shape your success, habits, and mindset.",
    authorImage: "https://i.pravatar.cc/150?img=22",
    authorBio: "Michael Reed is a motivational author who focuses on productivity and positive psychology."
  },
   {
    id: "book_atomic",
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self Improvement",
    image: "https://m.media-amazon.com/images/I/71g2ednj0JL._AC_UF1000,1000_QL80_.jpg",
    description: "A practical guide to building good habits and breaking bad ones to transform your life.",
     authorBio: "Michael Reed is a motivational author who focuses on productivity and positive psychology."
  },
  {
    id: "book_deepwork",
    title: "Deep Work",
    author: "Cal Newport",
    category: "Self Improvement",
    image: "https://m.media-amazon.com/images/I/81N7FmJhbhL._AC_UF1000,1000_QL80_.jpg",
    description: "Rules for focused success in a distracted world.",
     authorBio: "Michael Reed is a motivational author who focuses on productivity and positive psychology."
  },

  {
    id: "book_mindset",
    title: "Mindset",
    author: "Carol S. Dweck",
    category: "Self Improvement",
    image: "https://m.media-amazon.com/images/I/81-QB7nDh4L._AC_UF1000,1000_QL80_.jpg",
    description: "How our mindset shapes our success in learning, business, and relationships.",
     authorBio: "Michael Reed is a motivational author who focuses on productivity and positive psychology."
  },
  {
    id: "book_subtleart",
    title: "The Subtle Art ",
    author: "Mark Manson",
    category: "Self Improvement",
    image: "https://m.media-amazon.com/images/I/81eB+7+CkUL._AC_UF1000,1000_QL80_.jpg",
    description: "A counterintuitive approach to living a good life.",
     authorBio: "Michael Reed is a motivational author who focuses on productivity and positive psychology."
  },
  {
    id: "book_goggins",
    title: "Can't Hurt Me",
    author: "David Goggins",
    category: "Self Improvement",
    image: "https://m.media-amazon.com/images/I/81wgcld4wxL._AC_UF1000,1000_QL80_.jpg",
    description: "A powerful memoir about mastering your mind and defying the odds.",
     authorBio: "Michael Reed is a motivational author who focuses on productivity and positive psychology."
  }
];